In [1]:
#simpsons years/seasons

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from unicodedata import normalize

In [2]:
seasons = pd.read_html('https://en.wikipedia.org/wiki/The_Simpsons')

In [4]:
print(f'Total tables: {len(seasons)}')

Total tables: 27

In [7]:
GetSeasons = pd.read_html('https://en.wikipedia.org/wiki/The_Simpsons')[1]

In [8]:
GetSeasons

   Season            No. ofepisodes    Originally aired                   \
   Season            No. ofepisodes     Season premiere    Season finale
   Season   Season.1 No. ofepisodes     Season premiere    Season finale
0       1    1989–90             13   December 17, 1989     May 13, 1990
1       2    1990–91             22    October 11, 1990    July 11, 1991
2       3    1991–92             24  September 19, 1991  August 27, 1992
3       4    1992–93             22  September 24, 1992     May 13, 1993
4       5    1993–94             22  September 30, 1993     May 19, 1994
5       6    1994–95             25   September 4, 1994     May 21, 1995
6       7    1995–96             25  September 17, 1995     May 19, 1996
7       8    1996–97             25    October 27, 1996     May 18, 1997
8       9    1997–98             25  September 21, 1997     May 17, 1998
9      10    1998–99             23     August 23, 1998     May 16, 1999
10     11  1999–2000             22  September 26, 1999     May 21, 2000
11     12    2000–01             21    November 1, 2000     May 20, 2001
12     13    2001–02             22    November 6, 2001     May 22, 2002
13     14    2002–03             22    November 3, 2002     May 18, 2003
14     15    2003–04             22    November 2, 2003     May 23, 2004
15     16    2004–05             21    November 7, 2004     May 15, 2005
16     17    2005–06             22  September 11, 2005     May 21, 2006
17     18    2006–07             22  September 10, 2006     May 20, 2007
18     19    2007–08             20  September 23, 2007     May 18, 2008
19     20    2008–09             21  September 28, 2008     May 17, 2009
20     21    2009–10             23  September 27, 2009     May 23, 2010
21     22    2010–11             22  September 26, 2010     May 22, 2011
22     23    2011–12             22  September 25, 2011     May 20, 2012
23     24    2012–13             22  September 30, 2012     May 19, 2013
24     25    2013–14             22  September 29, 2013     May 18, 2014
25     26    2014–15             22  September 28, 2014     May 17, 2015
26     27    2015–16             22  September 27, 2015     May 22, 2016
27     28    2016–17             22  September 25, 2016     May 21, 2017
28     29    2017–18             21     October 1, 2017     May 20, 2018
29     30    2018–19             23  September 30, 2018     May 12, 2019
30     31    2019–20             22  September 29, 2019     May 17, 2020
31     32    2020–21            TBA  September 27, 2020              TBA

                                                       \
                                       Time Slot (ET)
                                       Time Slot (ET)
0                                      Sunday 8:30 pm
1                                    Thursday 8:00 pm
2                                    Thursday 8:00 pm
3                                    Thursday 8:00 pm
4                                    Thursday 8:00 pm
5                                      Sunday 8:00 pm
6                                      Sunday 8:00 pm
7   Sunday 8:30 pm (Episodes 1–3)Sunday 8:00 pm (E...
8                                      Sunday 8:00 pm
9                                      Sunday 8:00 pm
10                                     Sunday 8:00 pm
11                                     Sunday 8:00 pm
12  Tuesday 8:30 pm (Episode 1)Sunday 8:00 pm (Epi...
13  Sunday 8:00 pm (Episodes 1–11, 13–21)Sunday 8:...
14                                     Sunday 8:00 pm
15  Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20)Sun...
16                                     Sunday 8:00 pm
17                                     Sunday 8:00 pm
18                                     Sunday 8:00 pm
19                                     Sunday 8:00 pm
20                                     Sunday 8:00 pm
21                                     Sunday 8:00 pm
22                                     Sunday 8:00 pm
23                                     Sunday 8:00 pm
24                                     Sunday 8:00 pm
25                                     Sunday 8:00 pm
26                                     Sunday 8:00 pm
27                                     Sunday 8:00 pm
28                                     Sunday 8:00 pm
29                                     Sunday 8:00 pm
30                                     Sunday 8:00 pm
31                                                NaN

                  Viewership                       \
   Avg. viewers(in millions) Most watched episode
   Avg. viewers(in millions)    Viewers(millions)
0                       27.8                 33.5
1                       24.4                 33.6
2                       21.8                 25.5
3                       22.4                 28.6
4                       18.9                 24.0
5                       15.6                 22.2
6                       15.1                 19.7
7                       14.5                 20.9
8                       15.3                 19.8
9                       13.5                 15.5
10                       8.8                 18.4
11                      15.5                 18.6
12                      12.5                 14.9
13                      14.4                 22.1
14                      11.0                 16.3
15                      10.2                23.07
16                      9.55                11.63
17                      9.15                13.90
18                      8.37                 11.7
19                       7.1                 12.4
20                       7.1                14.62
21                      7.09                 12.6
22                 6.15[149]                11.48
23                 5.41[150]                 8.97
24                 5.02[151]                12.04
25                 5.61[152]                10.62
26                  4.0[153]                 8.33
27                 4.80[154]                 8.19
28                 4.07[155]                 8.04
29                 3.10[156]                 8.20
30                 2.58[157]                 5.63
31                       TBA                  TBA



                           Episode Title
0                "Life on the Fast Lane"
1                       "Bart Gets an F"
2                        "Colonel Homer"
3                    "Lisa's First Word"
4               "Treehouse of Horror IV"
5                "Treehouse of Horror V"
6               "Treehouse of Horror VI"
7                "The Springfield Files"
8     "The Two Mrs. Nahasapeemapetilons"
9                   "Maximum Homerdrive"
10                  "The Mansion Family"
11                  "Worst Episode Ever"
12                      "The Parent Rap"
13       "I'm Spelling as Fast as I Can"
14              "I, (Annoyed Grunt)-Bot"
15      "Homer and Ned's Hail Mary Pass"
16             "Treehouse of Horror XVI"
17                    "The Wife Aquatic"
18           "Treehouse of Horror XVIII"
19             "Treehouse of Horror XIX"
20     "Once Upon a Time in Springfield"
21             "Moms I'd Like to Forget"
22               "The D'oh-cial Network"
23           "Homer Goes to Prep School"
24                  "Steal This Episode"
25       "The Man Who Came to Be Dinner"
26  "Teenage Mutant Milk-Caused Hurdles"
27                      "Pork and Burns"
28                    "Frink Gets Testy"
29                 "The Girl on the Bus"
30                  "Go Big or Go Homer"
31                                   TBA

In [10]:
GetSeasons.columns

MultiIndex([(          'Season',                    'Season', ...),
            (          'Season',                    'Season', ...),
            (  'No. ofepisodes',            'No. ofepisodes', ...),
            ('Originally aired',           'Season premiere', ...),
            ('Originally aired',             'Season finale', ...),
            ('Originally aired',            'Time Slot (ET)', ...),
            (      'Viewership', 'Avg. viewers(in millions)', ...),
            (      'Viewership',      'Most watched episode', ...),
            (      'Viewership',      'Most watched episode', ...)],
           )

In [29]:
SeasonsTable = GetSeasons[('Season', 'Season', 'Season.1')]

In [24]:
SeasonsTableDF = pd.DataFrame(SeasonsTable)

In [25]:
SeasonsTableDF

       Season
       Season
     Season.1
0     1989–90
1     1990–91
2     1991–92
3     1992–93
4     1993–94
5     1994–95
6     1995–96
7     1996–97
8     1997–98
9     1998–99
10  1999–2000
11    2000–01
12    2001–02
13    2002–03
14    2003–04
15    2004–05
16    2005–06
17    2006–07
18    2007–08
19    2008–09
20    2009–10
21    2010–11
22    2011–12
23    2012–13
24    2013–14
25    2014–15
26    2015–16
27    2016–17
28    2017–18
29    2018–19
30    2019–20
31    2020–21

In [27]:
SeasonsTableDF.columns

MultiIndex([('Season', 'Season', 'Season.1')],
           )

In [30]:
SeasonsTable2 = GetSeasons[('Season', 'Season', 'Season')]

In [32]:
SeasonsDF = pd.DataFrame(SeasonsTable2)

In [39]:
SeasonsDF.reset_index()

   index Season
         Season
         Season
0      0      1
1      1      2
2      2      3
3      3      4
4      4      5
5      5      6
6      6      7
7      7      8
8      8      9
9      9     10
10    10     11
11    11     12
12    12     13
13    13     14
14    14     15
15    15     16
16    16     17
17    17     18
18    18     19
19    19     20
20    20     21
21    21     22
22    22     23
23    23     24
24    24     25
25    25     26
26    26     27
27    27     28
28    28     29
29    29     30
30    30     31
31    31     32

In [41]:
SeasonsDF.columns = ['Seasons']

In [44]:
SeasonsDF

    Seasons
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
10       11
11       12
12       13
13       14
14       15
15       16
16       17
17       18
18       19
19       20
20       21
21       22
22       23
23       24
24       25
25       26
26       27
27       28
28       29
29       30
30       31
31       32

In [45]:
SeasonsTableDF.reset_index()

   index     Season
             Season
           Season.1
0      0    1989–90
1      1    1990–91
2      2    1991–92
3      3    1992–93
4      4    1993–94
5      5    1994–95
6      6    1995–96
7      7    1996–97
8      8    1997–98
9      9    1998–99
10    10  1999–2000
11    11    2000–01
12    12    2001–02
13    13    2002–03
14    14    2003–04
15    15    2004–05
16    16    2005–06
17    17    2006–07
18    18    2007–08
19    19    2008–09
20    20    2009–10
21    21    2010–11
22    22    2011–12
23    23    2012–13
24    24    2013–14
25    25    2014–15
26    26    2015–16
27    27    2016–17
28    28    2017–18
29    29    2018–19
30    30    2019–20
31    31    2020–21

In [46]:
SeasonsTableDF.columns = ['Years']

In [47]:
SeasonsTableDF

        Years
0     1989–90
1     1990–91
2     1991–92
3     1992–93
4     1993–94
5     1994–95
6     1995–96
7     1996–97
8     1997–98
9     1998–99
10  1999–2000
11    2000–01
12    2001–02
13    2002–03
14    2003–04
15    2004–05
16    2005–06
17    2006–07
18    2007–08
19    2008–09
20    2009–10
21    2010–11
22    2011–12
23    2012–13
24    2013–14
25    2014–15
26    2015–16
27    2016–17
28    2017–18
29    2018–19
30    2019–20
31    2020–21

In [51]:
AllSeasons = SeasonsDF.join(SeasonsTableDF)

In [52]:
AllSeasons

    Seasons      Years
0         1    1989–90
1         2    1990–91
2         3    1991–92
3         4    1992–93
4         5    1993–94
5         6    1994–95
6         7    1995–96
7         8    1996–97
8         9    1997–98
9        10    1998–99
10       11  1999–2000
11       12    2000–01
12       13    2001–02
13       14    2002–03
14       15    2003–04
15       16    2004–05
16       17    2005–06
17       18    2006–07
18       19    2007–08
19       20    2008–09
20       21    2009–10
21       22    2010–11
22       23    2011–12
23       24    2012–13
24       25    2013–14
25       26    2014–15
26       27    2015–16
27       28    2016–17
28       29    2017–18
29       30    2018–19
30       31    2019–20
31       32    2020–21

In [54]:
AllSeasons[('Seasons')] = AllSeasons[('Seasons')].astype(int)

In [58]:
AllSeasons.dtypes

Seasons     int64
Years      object
dtype: object

In [59]:
AllSeasons.to_csv(r'/Users/christinemagnotta/Excellent-Simpsons-Analysis/AllSeasons.csv')